{{- if and (eq .Values.auth.type "oidc") .Values.auth.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-manager.fullname" . }}-secrets
  labels:
    {{- include "redis-manager.labels" . | nindent 4 }}
type: Opaque
data:
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
{{- end }}
